# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ben Plummer
tagline:          'A Jekyll theme'
description:      'PhD student at the <a href="https://www.southampton.ac.uk/" target="_blank">University of Southampton</a>.'
url:              https://benp.dev
baseurl:          /

author:
  name:           'Ben Plummer'
  #  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ben-plummer/ben-plummer.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist

